apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:csgo| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing [b]Counter-Strike: Global Offensive[/b].
    Counter-Strike: Global Offensive (CS:GO) is an online first-person shooter video
    game developed by Hidden Path Entertainment and Valve Corporation
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    [b]Important![/b] Before the order you should get steam token from http://steamcommunity.com/dev/managegameservers
    Please add AppID "730" and disired description for your new CS:GO server.
    Copy "Login Token" and add it into the field "Steam Token"
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]CS:GO![/b]
    Please find more information about CS:GO software on the official website [url]http://counter-strike.net[/url]
    Your server is ready and you can use %PUBLIC_ADDRESS% to access your server.

  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: memcached
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 0
          containers:
            - name: csgo
              kubes: 7
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: csgo
              kubes: 7
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: csgo
              kubes: 7
spec:
  template:
    metadata:
      labels:
        name: $APP_NAME$
    spec:
      restartPolicy: "Always"
      containers:
        -
          name: csgo
          image: hub.kuberdock.com/csgo:1
          args:
            - -game
            - csgo
            - -console
            - -usercon
            - +game_type
            - "$GAME_TYPE|default:0|Choose game type$"
            - +game_mode
            - "$GAME_MODE|default:0|Choose game mode$"
            - +mapgroup
            - $MAP_GROUP|default:mg_bomb|Choose map group$
            - +map
            - $MAP|default:de_dust2|Choose your map$
            - +sv_setsteamaccount
            - $STEAM_TOKEN|default:|Insert your Steam Token$
          ports:
            - containerPort: 27015
              podPort: 27015
              protocol: TCP
              isPublic: True
            - containerPort: 27015
              podPort: 27015
              protocol: UDP
              isPublic: True

