apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:drupal| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]Drupal[/b].
    Drupal is an open source content management platform powering millions of websites and applications.
    All the components needed for this application correct work will also be installed: [b]MySQL[/b] server.
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]Drupal![/b]
    Please find more information about Drupal software on the official website [url]https://www.drupal.org/[/url]
    To access [b]Drupal[/b] use this link: [url]http://%PUBLIC_ADDRESS%[/url]
    You can access [b]MySQL[/b] using credentials:
    [b]Host:[/b] 127.0.0.1
    [b]Database:[/b] drupal
    [b]Login:[/b] drupal
    [b]Password:[/b]  $MYSQL_USER_PASSWORD$

    We recommend you to save the credentials.

  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: drupal
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 0
          containers:
            - name: mysql
              kubes: 6
            - name: drupal
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: drupal-persistent-storage
              pdSize: 1
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 6
            - name: drupal
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: drupal-persistent-storage
              pdSize: 1
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: mysql
              kubes: 6
            - name: drupal
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 2
            - name: drupal-persistent-storage
              pdSize: 2
spec:
  template:
    metadata:
      labels:
        name: $APP_NAME$
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentDisk:
            pdName: drupal_mysql_$PD_RAND|default:autogen|PD rand$
        - name: drupal-persistent-storage
          persistentDisk:
            pdName: drupal_html_$PD_RAND$
      restartPolicy: "Always"
      containers:
        -
          name: mysql
          image: kuberdock/mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: drupal
            - name: MYSQL_USER
              value: drupal
            - name: MYSQL_PASSWORD
              value: $MYSQL_USER_PASSWORD|default:autogen|mysql user password$
            - name: MYSQL_ROOT_PASSWORD
              value: $MYSQL_ROOT_PASSWORD|default:autogen|mysql root password$
            - name: MYSQL_AUTO_MEMORY_ALLOCATE
              value: $MYSQL_AUTO_MEMORY_ALLOCATE|default:innodb|Please choose default MySQL engine "innodb" or "myisam"$
          ports:
            - containerPort: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
        -
          name: drupal
          image: drupal:8
          ports:
            - containerPort: 80
              isPublic: True
          readinessProbe:
            httpGet:
              path: /
              scheme: HTTP
              port: 80
            timeoutSeconds: 30
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /var/www/html
              name: drupal-persistent-storage
              kdCopyFromImage: true
          workingDir: /var/www/html

