apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:opencart| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]OpenCart[/b].
    An open source PHP-based online e-commerce solution.
    All the components needed for this application correct work will also be installed: [b]MySQL[/b] server.
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]OpenCart![/b]
    Please find more information about OpenCart software on the official website [url]http://www.opencart.com/[/url]
    To access [b]OpenCart[/b] use this link: [url]http://%PUBLIC_ADDRESS%[/url]
    You can access [b]MySQL[/b] using credentials:
    [b]Host:[/b] 127.0.0.1
    [b]Database:[/b] opencart
    [b]Login:[/b] opencart
    [b]Password:[/b] $MYSQL_USER_PASSWORD$

    We recommend you to save the credentials.

    Please, restart pod after installation.

  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: opencart
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 0
          containers:
            - name: mysql
              kubes: 6
            - name: opencart
              kubes: 1
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: opencart-persistent-storage
              pdSize: 1
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 6
            - name: opencart
              kubes: 1
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: opencart-persistent-storage
              pdSize: 1
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: mysql
              kubes: 6
            - name: opencart
              kubes: 1
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 2
            - name: opencart-persistent-storage
              pdSize: 2
spec:
  template:
      metadata:
        labels:
          name: $APP_NAME$
      spec:
        volumes:
          - name: mysql-persistent-storage
            persistentDisk:
              pdName: opencart_mysql_$PD_RAND|default:autogen|PD rand$
          - name: opencart-persistent-storage
            persistentDisk:
                pdName: opencart_www_$PD_RAND$
        restartPolicy: "Always"
        containers:
          -
            name: mysql
            image: kuberdock/mysql:5.7
            env:
              - name: MYSQL_DATABASE
                value: opencart
              - name: MYSQL_USER
                value: opencart
              - name: MYSQL_PASSWORD
                value: $MYSQL_USER_PASSWORD|default:autogen|mysql password$
              - name: MYSQL_ROOT_PASSWORD
                value: $MYSQL_ROOT_PASSWORD|default:autogen|mysql password$
              - name: MYSQL_AUTO_MEMORY_ALLOCATE
                value: $MYSQL_AUTO_MEMORY_ALLOCATE|default:innodb|Please choose default MySQL engine "innodb" or "myisam"$
            ports:
              - containerPort: 3306
            readinessProbe:
              tcpSocket:
                port: 3306
              initialDelaySeconds: 5
            volumeMounts:
              - mountPath: /var/lib/mysql
                name: mysql-persistent-storage
          -
            name: opencart
            image: kuberdock/opencart:2.2.0.0
            ports:
              - containerPort: 80
                isPublic: True
            readinessProbe:
              httpGet:
                path: /
                scheme: HTTP
                port: 80
              initialDelaySeconds: 5
            volumeMounts:
                - mountPath: /var/www/html
                  name: opencart-persistent-storage
                  kdCopyFromImage: true
            workingDir: /var/www/html

