apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:phpmyadmin| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]PHPMyAdmin[/b].
    phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web.
    All the components needed for this application correct work will also be installed: [b]MySQL[/b] server.
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]PHPMyAdmin![/b]
    Please find more information about PHPMyAdmin software on the official website [url]https://www.phpmyadmin.net/[/url]
    To access [b]PHPMyAdmin[/b] use this link: [url]http://%PUBLIC_ADDRESS%:$PHPMYADM_HOST_PORT$[/url]
    [b]MySQL[/b] info is the following:
    Database: $MYSQL_DATABASE$
    User: $MYSQL_USER$
    MySQL user password: $MYSQL_USER_PASSWORD$
    MySQL root password: $MYSQL_ROOT_PASSWORD$

  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: phpmyadmin
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 0
          containers:
            - name: mysql
              kubes: 6
            - name: phpmyadmin
              kubes: 2
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 6
            - name: phpmyadmin
              kubes: 3
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: mysql
              kubes: 6
            - name: phpmyadmin
              kubes: 3
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 2
spec:
  template:
    metadata:
      labels:
        name: $APP_NAME$
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentDisk:
            pdName: pma_mysql_$PD_RAND|default:autogen|PD rand$
        - name: pma-persistent-storage
      restartPolicy: "Always"
      containers:
        -
          name: mysql
          image: kuberdock/mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: $MYSQL_DATABASE|default:mydata|Please type appropriate database name$
            - name: MYSQL_USER
              value: $MYSQL_USER|default:user|Pleae choose your database user$
            - name: MYSQL_PASSWORD
              value: $MYSQL_USER_PASSWORD|default:autogen|mysql password$
            - name: MYSQL_ROOT_PASSWORD
              value: $MYSQL_ROOT_PASSWORD|default:autogen|mysql password$
            - name: MYSQL_AUTO_MEMORY_ALLOCATE
              value: $MYSQL_AUTO_MEMORY_ALLOCATE|default:innodb|Please choose default MySQL engine "innodb" or "myisam"$
          ports:
            - containerPort: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
        -
          name: phpmyadmin
          image: dnhsoft/phpmyadmin:4.6.4
          env:
            - name: DBHOST
              value: 127.0.0.1
            - name: DBUSER
              value: $MYSQL_USER$
            - name: DBPASS
              value: $MYSQL_USER_PASSWORD$
          ports:
            - containerPort: 80
              podPort: $PHPMYADM_HOST_PORT|default:80|Enter phpmyadmin host port$
              isPublic: True
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
          workingDir: /var/www/html

