apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:redmine| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]Redmine[/b].
    Redmine is a flexible project management web application written using Ruby on Rails framework
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]Redmine![/b]
    Please find more information about Redmine software on the official website [url]http://www.redmine.org/[/url]
    To access [b]Redmine[/b] use this link: [url]http://%PUBLIC_ADDRESS%:$REDMINE_HOST_PORT$[/url]
    You can access [b]MySQL[/b] using credentials:
    [b]Host:[/b] 127.0.0.1
    [b]Database:[/b] redmine
    [b]Login:[/b] redmine
    [b]Password:[/b] $MYSQL_USER_PASSWORD$

    Please, read the application documentation: [url]http://www.redmine.org/projects/redmine/wiki/[/url]

    [b]Important![/b] The default username and password are admin/admin. We strongly recommend to change
    Redmine password after login to something more secure from Adminitration > Users

  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: redmine
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 0
          containers:
            - name: mysql
              kubes: 6
            - name: redmine
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: redmine-persistent-storage
              pdSize: 1
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 6
            - name: redmine
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: redmine-persistent-storage
              pdSize: 1
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: mysql
              kubes: 6
            - name: redmine
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 2
            - name: redmine-persistent-storage
              pdSize: 2
spec:
  template:
    metadata:
      labels:
        name: $APP_NAME$
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentDisk:
            pdName: redmine_mysql_$PD_RAND|default:autogen|PD rand$
        - name: redmine-persistent-storage
          persistentDisk:
            pdName: redmine_files_$PD_RAND$
      restartPolicy: "Always"
      resolve: [mysql]
      containers:
        -
          name: mysql
          image: kuberdock/mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: redmine
            - name: MYSQL_USER
              value: redmine
            - name: MYSQL_PASSWORD
              value: $MYSQL_USER_PASSWORD|default:autogen|mysql user password$
            - name: MYSQL_ROOT_PASSWORD
              value: $MYSQL_ROOT_PASSWORD|default:autogen|mysql root password$
            - name: MYSQL_AUTO_MEMORY_ALLOCATE
              value: $MYSQL_AUTO_MEMORY_ALLOCATE|default:innodb|Please choose default MySQL engine "innodb" or "myisam"$
          ports:
            - containerPort: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
        -
          name: redmine
          image: redmine:3
          env:
            - name: MYSQL_PORT_3306_TCP
              value: "3306"
            - name: MYSQL_ENV_MYSQL_DATABASE
              value: redmine
            - name: MYSQL_ENV_MYSQL_USER
              value: redmine
            - name: MYSQL_ENV_MYSQL_PASSWORD
              value: $MYSQL_USER_PASSWORD$
          ports:
            - containerPort: 3000
              podPort: $REDMINE_HOST_PORT|default:3000|Enter Redmine host port$
              isPublic: True
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /usr/src/redmine/files
              name: redmine-persistent-storage
          workingDir: /usr/src/redmine

